import type { BusinessType, BusinessTypeTemplatePreview } from "../types";

export const BUSINESS_TYPE_PREVIEWS: Record<BusinessType, BusinessTypeTemplatePreview[]> = {
  MEDICAL: [
    {
      name: "Owner",
      description: "Full system administration and unrestricted organizational access",
      isSystem: true,
      permissions: ["23 permissions (Full Access)"],
    },
    {
      name: "Pharmacist",
      description: "Dispenses medications, reviews inventory, and validates sales orders",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
        "SALE_VIEW",
        "SALE_CREATE",
        "SALE_UPDATE",
        "SUPPLIER_VIEW",
        "REPORT_VIEW",
      ],
    },
    {
      name: "Billing Staff",
      description: "Handles customer checkout, invoice generation, and sales records",
      permissions: [
        "PRODUCT_VIEW",
        "STOCK_VIEW",
        "SALE_VIEW",
        "SALE_CREATE",
        "SALE_UPDATE",
      ],
    },
    {
      name: "Inventory Staff",
      description: "Receives pharmaceutical stock, manages batch counts, and suppliers",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
        "SUPPLIER_VIEW",
        "SUPPLIER_CREATE",
      ],
    },
  ],

  FURNITURE: [
    {
      name: "Owner",
      description: "Full system administration and unrestricted organizational access",
      isSystem: true,
      permissions: ["23 permissions (Full Access)"],
    },
    {
      name: "Store Manager",
      description: "Oversees furniture showroom, team invitations, and sales operations",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
        "SALE_VIEW",
        "SALE_CREATE",
        "SALE_UPDATE",
        "SALE_CANCEL",
        "SUPPLIER_VIEW",
        "EMPLOYEE_VIEW",
        "EMPLOYEE_INVITE",
        "REPORT_VIEW",
      ],
    },
    {
      name: "Sales Staff",
      description: "Configures furniture orders, customer quotes, and sales transactions",
      permissions: [
        "PRODUCT_VIEW",
        "STOCK_VIEW",
        "SALE_VIEW",
        "SALE_CREATE",
        "SALE_UPDATE",
      ],
    },
    {
      name: "Inventory Staff",
      description: "Manages warehouse intake for large furniture items and audits",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
        "SUPPLIER_VIEW",
      ],
    },
    {
      name: "Delivery Staff",
      description: "Verifies delivery shipments, dispatches, and inventory levels",
      permissions: ["PRODUCT_VIEW", "STOCK_VIEW", "SALE_VIEW"],
    },
  ],

  ELECTRONICS: [
    {
      name: "Owner",
      description: "Full system administration and unrestricted organizational access",
      isSystem: true,
      permissions: ["23 permissions (Full Access)"],
    },
    {
      name: "Store Manager",
      description: "Supervises electronics showroom, staff scheduling, and high-value inventory",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
        "SALE_VIEW",
        "SALE_CREATE",
        "SALE_UPDATE",
        "SALE_CANCEL",
        "SUPPLIER_VIEW",
        "EMPLOYEE_VIEW",
        "EMPLOYEE_INVITE",
        "REPORT_VIEW",
      ],
    },
    {
      name: "Sales Staff",
      description: "Assists retail customers, generates invoices and warranty sales",
      permissions: [
        "PRODUCT_VIEW",
        "STOCK_VIEW",
        "SALE_VIEW",
        "SALE_CREATE",
      ],
    },
    {
      name: "Technician",
      description: "Handles diagnostic repairs, replacement parts, and component stock adjustments",
      permissions: [
        "PRODUCT_VIEW",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
      ],
    },
    {
      name: "Inventory Staff",
      description: "Tracks serialized stock intake, returns, and supplier replenishment",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
        "SUPPLIER_VIEW",
      ],
    },
  ],

  FASHION: [
    {
      name: "Owner",
      description: "Full system administration and unrestricted organizational access",
      isSystem: true,
      permissions: ["23 permissions (Full Access)"],
    },
    {
      name: "Store Manager",
      description: "Manages boutique staff, collection changes, and discounts",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
        "SALE_VIEW",
        "SALE_CREATE",
        "SALE_UPDATE",
        "SALE_CANCEL",
        "EMPLOYEE_VIEW",
        "REPORT_VIEW",
      ],
    },
    {
      name: "Sales Staff",
      description: "Assists retail clients, records boutique sales transactions",
      permissions: [
        "PRODUCT_VIEW",
        "STOCK_VIEW",
        "SALE_VIEW",
        "SALE_CREATE",
      ],
    },
    {
      name: "Inventory Staff",
      description: "Manages garment sizes, colors, stockroom replenishment",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
      ],
    },
  ],

  GENERAL: [
    {
      name: "Owner",
      description: "Full system administration and unrestricted organizational access",
      isSystem: true,
      permissions: ["23 permissions (Full Access)"],
    },
    {
      name: "Manager",
      description: "Oversees general operations, staff, inventory and sales",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
        "SALE_VIEW",
        "SALE_CREATE",
        "SALE_UPDATE",
        "SALE_CANCEL",
        "EMPLOYEE_VIEW",
        "REPORT_VIEW",
      ],
    },
    {
      name: "Sales Staff",
      description: "Records register sales and basic catalogue inquiries",
      permissions: [
        "PRODUCT_VIEW",
        "STOCK_VIEW",
        "SALE_VIEW",
        "SALE_CREATE",
      ],
    },
    {
      name: "Inventory Staff",
      description: "Updates shelf stock and records supplier intake",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
      ],
    },
  ],

  OTHER: [
    {
      name: "Owner",
      description: "Full system administration and unrestricted organizational access",
      isSystem: true,
      permissions: ["23 permissions (Full Access)"],
    },
    {
      name: "Manager",
      description: "Oversees daily business operations and team members",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
        "SALE_VIEW",
        "SALE_CREATE",
        "SALE_UPDATE",
        "SALE_CANCEL",
        "EMPLOYEE_VIEW",
        "REPORT_VIEW",
      ],
    },
    {
      name: "Sales Staff",
      description: "Manages customer transactions and invoice orders",
      permissions: [
        "PRODUCT_VIEW",
        "STOCK_VIEW",
        "SALE_VIEW",
        "SALE_CREATE",
      ],
    },
    {
      name: "Inventory Staff",
      description: "Handles stock adjustments and product intake",
      permissions: [
        "PRODUCT_VIEW",
        "PRODUCT_CREATE",
        "PRODUCT_UPDATE",
        "STOCK_VIEW",
        "STOCK_UPDATE",
        "STOCK_ADJUST",
      ],
    },
  ],
};
